config/routes.rb
Enrollments::Application.routes.draw do
  resources :people do
    patch :confirm, on: :member
  end

  scope constraints: { email: /[^\/]+/ } do
    get 'registered/:id/:email', to: 'enrollments#show', as: 'registered'
    get 'thanks/:id/:email', to: 'thanks#index', as: 'thanks'
  end

  devise_for :users
  resources :users

  root to: 'people#new'
end

app/models/concerns/people/enrollments.rb
module People::Enrollments
  extend ActiveSupport::Concern

  included do
    delegate :last, to: :enrollments, prefix: true

    scope :with_notebook, -> {
      includes(:enrollments).where(enrollments: { with_notebook: true })
    }
    scope :without_notebook, -> {
      includes(:enrollments).where(enrollments: { with_notebook: false })
    }

    has_many :enrollments, dependent: :destroy
    accepts_nested_attributes_for :enrollments
  end
end

app/models/concerns/people/validations.rb
module People::Validations
  extend ActiveSupport::Concern

  included do
    before_validation :strip_whitespace

    validates :name, :lastname, :email, :identification, presence: true,
      length: { maximum: 255 }
    validates :email, :identification, uniqueness: { case_sensitive: false },
      allow_nil: true, allow_blank: true
    validates :email, uniqueness: { case_sensitive: false },
      format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  end

  def strip_whitespace
    self.name.try(:strip!)
    self.lastname.try(:strip!)
    self.email.try(:strip!).try(:downcase!)
    self.identification.try(:strip!).try(:downcase!)
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  include People::Enrollments
  include People::Validations

  scope :confirmed, -> { where(confirmed: true) }

  has_many :courses, through: :enrollments

  def to_s
    name
  end

  def confirm!
    update! confirmed: true
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only:  [:show, :edit, :update, :destroy, :confirm]
  before_action :set_courses, only: [:new, :create, :edit, :update]
  before_action :require_user, except: [:new, :create]

  layout ->(c) { c.request.xhr? ? false : 'application' }

  # GET /people
  def index
    @people = Person.page(params[:page]).order(:id)
    confirmed_people = Person.confirmed

    @with_notebook = confirmed_people.with_notebook.count
    @without_notebook = confirmed_people.without_notebook.count
  end

  # GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  def create
    @person = Person.new(person_params)

    if @person.save
      Notifier.delay.new_enrollment(@person.enrollments_last)

      redirect_to thanks_url(@person, email: @person.email)
    else
      check_if_already_enrolled
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      redirect_to @person, notice: t('view.people.correctly_updated')
    else
      render action: 'edit'
    end
  rescue ActiveRecord::StaleObjectError
    redirect_to edit_people_url(@user), alert: t('view.people.stale_object_error')
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url, notice: t('view.people.correctly_destroyed')
  end

  # PATCH /people/1/confirm
  def confirm
    @person.confirm!

    Notifier.delay.confirmed(@person.enrollments_last)

    if request.xhr?
      redirect_via_turbolinks_to people_url(page: params[:page])
    else
      redirect_to people_url(page: params[:page])
    end
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def set_courses
    @courses = Course.active
  end

  def check_if_already_enrolled
    person = Person.find_by(email: @person.email)

    if person && person.enrollments_last.present?
      redirect_to registered_url(person.enrollments_last, email: person.email)
    else
      render action: 'new'
    end
  end

  def person_params
    params.require(:person).permit(
      :name, :lastname, :email, :identification,
      enrollments_attributes: [:id, :course_id, :comment, :with_notebook]
    )
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def person_enrollment
    if action_name == 'new' || action_name == 'create'
      @person.enrollments.detect(&:new_record?) || @person.enrollments.build
    else
      @person.enrollments
    end
  end

  def with_notebook_enrollment_select(form)
    collection = [
      [t('view.enrollments.without_notebook'), false],
      [t('view.enrollments.with_notebook'), true]
    ]

    form.input :with_notebook, collection: collection, prompt: false,
      label: false, selected: form.object.try(:with_notebook)
  end

  def color_chooser_for_notebook(num)
    if num >= 15 && num < 20
      'label-warning'
    elsif num >= 20
      'label-danger'
    else
      'label-default'
    end
  end

  def link_to_confirm person
    options = {
      title: t('view.people.confirm'), method: :patch, data: { remote: true }
    }

    link_to confirm_person_path(person, page: params[:page]), options do
      content_tag :span, nil, class: 'glyphicon glyphicon-ok'
    end unless person.confirmed
  end

  def confirmed_label
    content_tag :label, t('label.yes'), class: 'label label-success'
  end

  def unconfirmed_label
    out = content_tag(:label, t('label.no'), class: 'label label-default')
    out << ' ' << link_to_confirm(@person)
  end
end

app/views/people/_form.html.erb
<%= simple_form_for @person do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-lg-3">
        <%= f.input :name, as: :slim, input_html: { autofocus: true } %>
      </div>
      <div class="col-lg-3">
        <%= f.input :lastname, as: :slim %>
      </div>
      <div class="col-lg-3">
        <%= f.input :email, as: :slim, type: :email_field %>
      </div>
      <div class="col-lg-3">
        <%= f.input :identification, as: :slim %>
      </div>
    </div>

    <%= f.simple_fields_for :enrollments, person_enrollment do |e_f| %>
      <div class="row">
        <div class="col-md-9">
          <%= e_f.association(
            :course, collection: @courses, label: false, include_blank: false
          ) %>
        </div>
        <div class="col-md-3">
          <%= with_notebook_enrollment_select(e_f) %>
        </div>
      </div>

      <%= e_f.input :comment, as: :slim, type: :text_area %>
    <% end %>
  </div>

  <div>
    <%= f.button :submit, class: 'btn-primary btn-lg' %>
  </div>
<% end %>

app/views/people/_person.html.erb
<tr class="<%= 'success' if person.confirmed%>">
  <td><%= link_to_confirm person %></td>
  <td><%= person.name %></td>
  <td><%= person.lastname %></td>
  <td><%= person.email %></td>
  <td><%= link_to_show person %></td>
  <td><%= link_to_edit edit_person_path(person) %></td>
  <td><%= link_to_destroy person %></td>
</tr>

app/views/people/edit.html.erb
<%= render 'form' %>

<%= link_to t('label.list'), people_path %>

app/views/people/index.html.erb
<div class="row">
  <div class="col-md-2">
    <p><%= t 'view.enrollments.confirmed', count: 0 %></p>
  </div>
  <div class="col-md-2">
    <p>
      <%= t 'view.enrollments.with_notebook' %>
      <span class="label <%= color_chooser_for_notebook @with_notebook %>">
        <%= @with_notebook %>
      </span>
    </p>
  </div>
  <div class="col-md-2">
    <p>
      <%= t 'view.enrollments.without_notebook' %>
      <span class="label <%= color_chooser_for_notebook @without_notebook %>">
        <%= @without_notebook %>
      </span>
    </p>
  </div>
</div>

<hr />

<table class="table table-condensed">
  <thead>
    <tr>
      <th></th>
      <th><%= Person.human_attribute_name 'name' %></th>
      <th><%= Person.human_attribute_name 'lastname' %></th>
      <th><%= Person.human_attribute_name 'email' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @people %>
  </tbody>
</table>

<%= pagination_links @people %>

app/views/people/new.es.html.erb
<div class="jumbotron">
  <h1>Hola <span id="name" class="text-warning"><%= @person.name %></span></h1>
  <h3>Contanos quien sos</h3>

  <%= render 'form' %>
</div>

<footer>
  <p class="text-muted small">
    (*) A nosotros tampoco nos gusta el correo que no pedimos, vamos a usar tu
    dirección solamente para temas relacionados con el curso
  </p>
</footer>

app/views/people/show.html.erb
<p>
  <strong><%= Person.human_attribute_name('name') %></strong>:
  <%= @person.name %>
</p>

<p>
  <strong><%= Person.human_attribute_name('lastname') %></strong>:
  <%= @person.lastname %>
</p>

<p>
  <strong><%= Person.human_attribute_name('email') %></strong>:
  <%= @person.email %>
</p>

<p>
  <strong><%= Person.human_attribute_name('identification') %></strong>:
  <%= @person.identification %>
</p>

<p>
  <strong><%= Person.human_attribute_name('confirmed') %></strong>:
  <%= @person.confirmed ? confirmed_label : unconfirmed_label %>
</p>

<% unless @person.enrollments.empty? %>
  <table class="table table-hover table-condensed table-bordered">
    <caption>
      <h3 class="text-left">
        <%= Enrollment.model_name.human count: @person.enrollments.count %>
      </h3>
    </caption>

    <thead>
      <tr>
        <th><%= Course.model_name.human %></th>
        <th><%= Enrollment.human_attribute_name 'with_notebook' %></th>
        <th><%= Enrollment.human_attribute_name 'comment' %></th>
      </tr>
    </thead>

    <tbody>
      <% @person.enrollments.each do |enrollment| %>
        <tr>
          <td><%= enrollment.course %></td>
          <td><%= enrollment.with_notebook ? t('label.yes') : t('label.no') %></td>
          <td><%= enrollment.comment %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to t('label.edit'), edit_person_path(@person) %> |
<%= link_to t('label.list'), people_path %>