config/routes.rb
Enrollments::Application.routes.draw do
  resources :people do
    patch :confirm, on: :member
  end

  scope constraints: { email: /[^\/]+/ } do
    get 'registered/:id/:email', to: 'enrollments#show', as: 'registered'
    get 'thanks/:id/:email', to: 'thanks#index', as: 'thanks'
  end

  devise_for :users
  resources :users

  root to: 'people#new'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  def to_s
    email
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @title = t 'view.users.index_title'
    @users = User.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /users/1
  def show
    @title = t 'view.users.show_title'

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /users/new
  def new
    @title = t 'view.users.new_title'
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @title = t 'view.users.edit_title'
  end

  # POST /users
  def create
    @title = t 'view.users.new_title'
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: t('view.users.correctly_created') }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH /users/1
  def update
    @title = t 'view.users.edit_title'

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: t('view.users.correctly_updated') }
      else
        format.html { render action: 'edit' }
      end
    end

  rescue ActiveRecord::StaleObjectError
    flash.alert = t 'view.users.stale_object_error'
    redirect_to edit_user_url(@user)
  end

  # DELETE /users/1
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email, :password, :password_confirmation, :remember_me, :lock_version
    )
  end
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, required: true, input_html: { maxlength: 255, autofocus: true } %>
    <%= f.input :password, required: true, input_html: { maxlength: 255 } %>
    <%= f.input :password_confirmation, input_html: { maxlength: 255 } %>
  </div>

  <div class="form-actions">
    <div class="pull-right"><%= yield :form_actions %></div>
    <%= f.input :lock_version, as: :hidden %>
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= mail_to user.email, user.email %></td>
  <td><%= link_to_edit edit_user_path(user) %></td>
  <td><%= link_to_destroy user %></td>
</tr>

app/views/users/edit.html.erb
<%= content_for :form_actions do %>
  <%= link_to t('label.show'), @user %> |
  <%= link_to t('label.list'), users_path %>
<% end %>

<%= render 'form' %>

app/views/users/index.html.erb
<% if @users.empty? %>
  <%= render 'shared/empty_index' %>
<% else %>
  <table class="table table-bordered table-hover table-striped" data-endless-container="true">
    <thead>
      <tr>
        <th><%= User.human_attribute_name 'email' %></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @users %>
    </tbody>
  </table>

  <%= pagination_links @users %>
<% end %>

<nav class="form-actions">
  <%= link_to(
    t('view.users.new', default: :'label.new'),
    new_user_path, class: 'btn btn-primary'
    ) %>
</nav>

app/views/users/new.html.erb
<%= content_for :form_actions do %>
  <%= link_to t('label.list'), users_path %>
<% end %>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="readonly-data">

  <p>
    <%= mail_to @user.email %>
  </p>

</div>

<div class="form-actions">
  <div class="pull-right">
    <%= link_to t('label.list'), users_path %>
  </div>
  <%= link_to t('label.edit'), edit_user_path(@user), class: 'btn btn-primary' %>
</div>